// SPDX-License-Identifier: LGPL-3.0-only
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. !!
pragma solidity ^0.8.4;

interface IMultisend {
  function multiSend(bytes memory transactions) external payable;
}
