// SPDX-License-Identifier: LGPL-3.0-only
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. !!
pragma solidity ^0.8.4;

interface ISignMessageLib {
    event SignMsg(bytes32 indexed msgHash);

    function getMessageHash(bytes memory message) external view returns (bytes32);

    function signMessage(bytes memory _data) external;
}
